<div id="flagForm">
    <form method="post" action="/pub/flag">
    <?php echo $this->element->type; ?>

    <hr />

    <div id="flagAddress">
        <?php echo $this->element->getSubForm('address'); ?>
    </div>

    <div id="flagDeal">
        <div id="dealSelector" class="left">
            <?php
            $i     = 0;
            $liquors = Model_LiquorType::getAllByName();

            while ($subForm = $this->element->getSubForm('detail' . $i)) {
                if ($subForm->getElement('id')->getValue()) {
                    $liquorType = $subForm->getElement('liquorType')->getValue();
                    $liquor = is_array($liquorType) ? $liquors[$liquorType[0]] : ''; ?>
                    <input type="radio" value="deal<?php echo $i; ?>" name="selector" id="selector<?php echo $i; ?>" <?php if ($i == 0) echo 'checked="checked"'; ?>/>
                        <label for="selector<?php echo $i; ?>">$<?php echo $subForm->getElement('value')->getValue() . ' ' . $liquor;?></label><br/>
                <?php }
                $i++;
            } ?>
        </div>
        <div id="dealSubforms">
            <?php
                $i = 0;
                while ($subForm = $this->element->getSubForm('detail' . $i)) {
                    if ($subForm->getElement('id')->getValue()) {
                        echo '<div id="deal' . $i . '">' . $this->element->getSubForm('detail' . $i) . '</div>';
                    }
                    $i++;
                } ?>
        </div>
    </div>

    <div style="text-align: right">
        <?php echo $this->element->submit; ?>
    </div>
    <?php echo $this->element->idPub; ?>
    </form>
</div>
<?php $this->placeholder('js')->captureStart(); ?>
<script type="text/javascript">

    $('#flagAddress, #flagDeal').hide();
    $(document).ready(function() {
        $('input[name="type"]').change(function() {
            switch (parseInt($(this).val())) {
                case <?php echo Model_Flag::FLAG_TYPE_CLOSED ?>:
                    $('#flagAddress, #flagDeal').hide();
                    break;
                case <?php echo Model_Flag::FLAG_TYPE_ADDRESS ?>:
                    $('#flagAddress').show();
                    $("#flagDeal").hide();
                    break;
                case <?php echo Model_Flag::FLAG_TYPE_PROMO ?>:
                    $('#flagAddress').hide();
                    $("#flagDeal").show();
                    break;
            }
        });

        $("#flagForm form").submit(function() {
            $.ajax({
                url: $(this).attr('action'),
                data: $(this).serialize(),
                type: 'post',
                success: function() {
                    if ($("#dialog").length) {
                        $("#dialog").dialog('close');
                    }
                }
            });
            return false;
        });

        $("input[name='selector']").change(function() {
            $("input[name='selector']").each(function() {
                if ($(this).is(':checked')) {
                    $("#" + $(this).val()).show();
                } else {
                    $("#" + $(this).val()).hide();
                }
            });
        }).change();


    });
</script>
<?php $this->placeholder('js')->captureEnd(); ?>