<?php $form = $this->element; ?>
<div>
	<form action="<?php echo $form->getAction(); ?>" method="post" class="<?php echo $form->getAttrib('class'); ?>">
	<div>By: <b><?php echo $this->escape($form->getRecord()->from); ?></b></div>
	<?php echo $form->subject; ?>
	<?php echo $form->hidden; ?>
	<?php echo $form->id; ?>
	<div class="image-region">
	<?php foreach($form->getRecord()->getImagesWebUri() as $image): ?>
		<div>
		<a data-image-path="<?php echo DOC_ROOT . $image; ?>" href="#" class="ss_sprite ss_arrow_rotate_anticlockwise anticlockwise">&nbsp;</a>
		<a data-image-path="<?php echo DOC_ROOT . $image; ?>" href="#" class="ss_sprite ss_arrow_rotate_clockwise clockwise">&nbsp;</a>
		<br />
		<a class="image" href="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=600"><img src="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=200&amp;h=200&amp;iar=1" /></a>
		</div>
	<?php endforeach; ?>
	</div>
	<dd id="<?php echo ($form->getName() ? $form->getName() . '-': null); ?>submit-element">
	<?php echo $form->submit->renderViewHelper(); ?> <a href="#" class="delete" data-mail="<?php echo $form->getRecord()->id; ?>">Delete</a>
	</dd>
	</form>
</div>