
<div id="about" class="content container">
    <div class="row">
        <div class="span10 offset1">
            <h1>About us</h1>
            <p>We know how hard it is to find a cheap watering hole these days. Who hasn't walked into a fancy bar
                to have a drink with the gang, only to find out that the cheapest cocktail sells for not less than $20?
                After suffering this situation too many times we felt like we could do something about it.
                That's how Dunia came to see the light, and the rest is history ;-).
            </p>
            <p>Dunia is developed by a group of friends with many things in common such us our passion for technology
                and our constant thirst for an affordable beverage.
            </p>
            <h2>Meet the team</h2>
        </div>
    </div>
    <div class="row team">
        <div class="span3 offset2">
            <img src="/img/victor.jpg" width="60" height="60"/>
            <h3>Victor</h3>
            <p><a href="https://twitter.com/#!/VictorGarcia">@VictorGarcia</a> </p>
        </div>
        <div class="span3">
            <img src="/img/avatar.gif" width="60" height="60"/>
            <h3>Jiangti</h3>
            <p></p>
        </div>
        <div class="span3">
            <img src="/img/avatar.gif" width="60" height="60"/>
            <h3>Gabriel</h3>
            <p></p>
        </div>
    </div>
</div>