<div class="container content" id="help">
    <div class="row-fluid">
        <div class="span3">
            <div class="sidebar-nav-fixed">
                <ul class="nav nav-list">
                    <li class="nav-header">Contributing</li>
                    <li><a href="#upload">Uploading Pictures</a></li>
                    <li><a href="#adding">Adding Happy Hours</a></li>
                    <li class="nav-header">General Usage</li>
                    <li><a href="#homepage">The homepage</a></li>
                </ul>
            </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
            <div class="hero-unit">
                <h1>Help me out!</h1>
                <p>Are you lost? Do you need help? Fear no more, for here you will learn how you can get the most out of Dunia and also how you can contribute to make it a better place!</p>
            </div>

            <div id="helpWrapper">
                <h2 id="upload">Uploading Pictures</h2>
                <div>
                    <p>Pictures... One of them is worth a thousand words. We love them! That's why we can't help ourselves every time we walk into a pub and see
                    a promotional poster. We love collecting them in our <em>pub pages</em>. If you are like us and you feel that urge to contribute when you
                    see a new <strong>happy hour</strong> promo here are the steps you need to follow:</p>

                    <ol>
                        <li>Take out your mobile phone and take a picture of the promotion.</li>
                        <li>Email that picture to <a class="email" href="mailto:to@dunia.com.au">to@dunia.com.au</a> indicating the <strong>pub name</strong> in the <em>subject</em>.</li>
                        <li>After a couple of minutes you will get an email with a link to the <strong>Mail Share</strong> page. Your picture will be listed first.</li>
                        <li>All you have to do is to fill up the name of the pub (we will hint you the closest one to the subject you sent) and then click the submit button.
                        You will then get a link to the <strong>pub page</strong> where you will be able to admire your picture!</li>
                        <li>You will notice there might still be more pictures there waiting to be processed by whoever uploaded them. If you are feeling super generous feel
                        free to classify them yourself! :)</li>
                    </ol>

                </div>
                <h2 id="adding">Adding Happy Hours</h2>
                <div>
                    <p>Uploading pictures is cool, but of course we are all here for the real deal, meaning the biggest promo in town!</p>
                    <p>We love our users, and that's why we give you guys full control over our promos. If you find a deal that we don't have, you are free
                    to add it up. If you detect a change in an existing happy hour, you are able to change it on the spot. All you have to do is navigate to
                    the <strong>pub page</strong> and click on the <strong>Edit</strong> button on top of the <em>Weekly Specials</em> timetable.</p>
                    <p>You can correct the data that is wrong, add a brand new promo or even remove an expired one. We keep track of all history changes so
                    don't worry if you messed up. We can always recover old information, after all we are human and we make mistakes ;-)</p>
                </div>
                <h2 id="homepage">The Homepage</h2>
                <div>
                    <p>We try to keep the homepage as simple as possible. That's why all you will find there is a map pointing to your closest area and filled
                    with markers that represent pubs. As you will realize this <em>pubs</em> are colour coded. Here is an explanation to what does each of
                    them mean:</p>

                    <ul>
                        <li class="itson">
                            <strong>It's on now!</strong> There is a happy hour going on at this place, Right. Now! So hurry up if you are on the move or you will miss it!
                        </li>
                        <li class="soon">
                            <strong>Coming soon</strong>: This pub has promos going on today and they haven't started yet, so you are in luck! There is still time for planning!
                        </li>
                        <li class="missed">
                            <strong>Missed it</strong>: Too late mate... You missed this one today. class="" We still want you to be aware of it though, as you might want to plan
                            your night better for next week :)
                        </li>
                        <li class="notoday">
                            <strong>Not today</strong>: These venues don't have an ongoing happy hour today but they do some other day of the week though. We thought you
                            might be interested in checking out what's on during the rest of the week so if you click on those you will be able to see all
                            the stuff they offer
                        </li>
                        <li class="zero">
                            <strong>Zero</strong>: We don't have any promotions for these venues but we know they are very hot spots. You might want to check them out and
                            who knows, maybe you find the next best deal and you come back and <a href="#adding">tell us all about it</a>.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
