<div class="navbar">
    <div id="header" class="navbar-inner">

        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <a id="logo" class="brand" href="/">Dunia</a>

        <form id="form">
            <?php echo $this->form->location; ?>
            <div style="margin-left: 300px; margin-top:-30px; width: 200px;">
            <fieldset style="border: none; margin: 0px; padding: 0px;">
                <label for="valueA" style="display:none;">From:</label>
                <select name="valueA" id="valueA" style="display:none;">
                    <option value="9:00" selected="selected">9:00</option>
                    <option value="10:00">10:00</option>
                    <option value="11:00">11:00</option>
                    <option value="12:00">Noon</option>
                    <option value="13:00">13:00</option>
                    <option value="14:00">14:00</option>
                    <option value="15:00">15:00</option>
                    <option value="16:00">16:00</option>
                    <option value="17:00">17:00</option>
                    <option value="18:00">18:00</option>
                    <option value="19:00">19:00</option>
                    <option value="20:00">20:00</option>
                    <option value="21:00">21:00</option>
                    <option value="22:00">22:00</option>
                    <option value="23:00">23:00</option>
                    <option value="24:00">24:00</option>
                </select>

                <label for="valueB" style="display:none;">To:</label>
                <select name="valueB" id="valueB" style="display:none;">
                    <option value="9:00">9:00</option>
                    <option value="10:00">10:00</option>
                    <option value="11:00">11:00</option>
                    <option value="12:00">Noon</option>
                    <option value="13:00">13:00</option>
                    <option value="14:00">14:00</option>
                    <option value="15:00">15:00</option>
                    <option value="16:00">16:00</option>
                    <option value="17:00">17:00</option>
                    <option value="18:00">18:00</option>
                    <option value="19:00">19:00</option>
                    <option value="20:00">20:00</option>
                    <option value="21:00">21:00</option>
                    <option value="22:00">22:00</option>
                    <option value="23:00">23:00</option>
                    <option value="24:00" selected="selected">24:00</option>
                </select>
            </fieldset>
            </div>
        </form>
        <?php echo $this->render('partials/nav.phtml'); ?>
    </div>
</div>
<div id="map_canvas" style="margin-top:-20px;height:95%;"></div>

<div id="bottom-info-bar">
	<div class="left summary" id="summary-bar" rel="popover">
		<script type="text/x-handlebars"  data-template-name="summary-bar">
		{{#each summaries}}
    		<a href="#" {{action "toggle"}}><img src="{{unbound smallIcon}}" />{{title}}: {{count}}</a>
		{{/each}}
		</script>
	</div>
	<div class="left">
        <?php echo $this->partial('partials/addthis.phtml'); ?>
	</div>
</div>

<script type="text/javascript">

$(document).ready(function() {

    $("#mailShare").popover({
        placement : 'bottom',
        content   : "In Mail Share you will find those pictures that fellow users have uploaded but haven't been " +
                    "processed yet. If you enjoy having the most accurate happy hour information help us by contributing!",
        title     : "Contribute",
        trigger   : 'manual'
    });

    $("#form input").popover({
        placement : 'bottom',
        content   : "Use the search box to look for your favorite pubs or explore different suburbs, " +
            "and filter the result using the time slider to see only promos going on when you are going out",
        title     : "Find what you need",
        trigger   : 'manual'
    });

    $("#summary-bar").popover({
        placement : 'top',
        content   : "This links give you information about venues offering happy hours right now, soon, " +
                    "or those that you just missed. You can click on them to toggle visibility.",
        title     : "What's going on?",
        trigger   : 'manual'
    });

    $("#help").hover(function() {
        $("#form input, #summary-bar, #mailShare").popover('toggle');
    })

	$('select#valueA, select#valueB').selectToUISlider({
		labels: 6,
		tooltip: false,
		sliderOptions: {
			stop: function() {
				var value0 = $('select#valueA').val();
				var value1 = $('select#valueB').val();
				AppMap.setMarkersByTime(value0, value1);
			}
		}
	});

    var amHere = new google.maps.LatLng('<?php echo $this->lat; ?>', '<?php echo $this->long; ?>');
    var myOptions = {
        zoom: <?php echo $this->zoom; ?>,
        maxZoom: 20,
        center: amHere,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        streetViewControl: true,
        overviewMapControl: true
    };


    AppMap = Dunia.Map.create({
        longitude: '<?php echo $this->long; ?>',
        latitude:  '<?php echo $this->lat; ?>',
        map:       new google.maps.Map(document.getElementById("map_canvas"), myOptions)
    });


    var input = document.getElementById('location');
    var autocomplete = new google.maps.places.Autocomplete(input);

    autocomplete.bindTo('bounds', AppMap.map);

	var view = Ember.View.create({
		templateName: 'summary-bar',
		summaries: Dunia.summary.summaries,
		toggle: function(event) {
			event.preventDefault();
			var object = event.context;

			object.set('flag', !(object.get('flag')));
			AppMap.setMarkersVisible(object.get('name'), object.get('flag'));
		}
	});

	view.appendTo('#summary-bar');

    google.maps.event.addListener(autocomplete, 'place_changed', function() {
        var place = autocomplete.getPlace();
        AppMap.cleanMarkers();
        AppMap.map.setCenter(place.geometry.location);
    });
    
    google.maps.event.addListener(AppMap.map, 'tilesloaded', function(event) {
    	AppMap.fetchBars();
    });

});
</script>


<?php $this->headScript()->appendFile('/contrib/selectToUiSlider/js/selectToUISlider.jQuery.js'); ?>
<?php $this->headLink()->appendStylesheet('/contrib/selectToUiSlider/css/ui.slider.extras.css'); ?>