<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!-- Add your page title -->
    <title>Dunia | Your source for Happy Hours and daily Pub Deals in the Sydney Area</title>
    <!-- Add your description here -->
    <meta name="description" content="Add a brief description about what you're working on.">
    <!-- Add your relevant author domain here -->
    <meta name="author" content="spking.com">
    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">


    <!-- CSS: implied media="all" -->
    <link rel="stylesheet" href="/css/landing-style.css?v=2">

</head>

<body>

<div id="container">
    <header>
        <div id="top">
            <!-- Replace with your logo -->
            <img src="/img/dunia.png">
        </div>
    </header>
    <div id="main" role="main">

        <h1>Welcome to Dunia!</h1>
        <h2>We are working hard to build the best collection of happy hours and pub deals in the wonderful city of Sydney! Sign up using the form below and be the first to benefit from Dunia. We are launching pretty soon!</h2>

        <div id="signup-box">
            <div id="email" class="clearfix">
                <form action="[put your form action url here]" method="post" id="subForm">
                    <input type="text" name="[put your input name here]" id="[put your input id here]" class="email_addr" placeholder="your email (we won't share it!)">
                    <button class="slick-black">Request an Invite</button>
                </form>
            </div>
        </div>
    </div>
    <footer>

    </footer>
</div> <!--! end of #container -->

<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-30515404-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

</body>
</html>