<script type="text/javascript">
    $(document).ready(function() {

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                Dunia.Location.setAddress(position);

                $.ajax({
                    type : 'POST',
                    url  : '/index/locate',
                    data : {long: position.coords.longitude, lat: position.coords.latitude},
                    success : function (data) {
                        $("#info").html(data);
                        $("#info").find('ul').listview();
                    }
                });
                
            }, 
            function (msg) {
                var s = document.querySelector('#info');
                s.innerHTML = typeof msg == 'string' ? msg : "failed";
                s.className = 'fail';
                
            });
        } else {
            $('#info').html('Geolocation is not supported :(');
        }
    });

</script>


<div id="info" style="text-align: center">
    <img src="/css/images/ajax-loader.png" width="35" height="35" />
    <p>Please wait while we locate you and find the closest deals.</p>
</div>

<div class="addthis_toolbox addthis_default_style ">
    <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
    <a class="addthis_button_tweet"></a>
    <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
    <a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f93fc3233f490f0"></script>
