<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Dunia | Happy Hours and Daily Pub Deals in Sydney | Cheap beer, wine, spirits</title>

    <meta name="description" content="Dunia brings you the most interesting Happy Hours and Pub deals in the city of Sydney, Australia. Cheap beer, wine and spirits.">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">


    <!-- CSS: implied media="all" -->
    <link rel="stylesheet" href="/css/landing-style.css?v=2">

</head>

<body>

<div id="container">
    <header>
        <div id="top">
            <img src="/img/dunia.png">
        </div>
    </header>
    <div id="main" role="main">

        <h1>Welcome to Dunia!</h1>
        <h2>We are working hard to build the best collection of happy hours and pub deals in the wonderful city of Sydney!
            If you want us to give you a shout once we are ready to go, just enter your email address in the form below or
            log in using your Facebook account. We are launching pretty soon!</h2>

        <?php echo $this->layout()->content; ?>

    </div>
    <footer>

    </footer>
</div> <!--! end of #container -->

<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-30515404-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

<script type="text/javascript" charset="utf-8">
    var is_ssl = ("https:" == document.location.protocol);
    var asset_host = is_ssl ? "https://d3rdqalhjaisuu.cloudfront.net/" : "http://d3rdqalhjaisuu.cloudfront.net/";
    document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
    var feedback_widget_options = {};

    feedback_widget_options.display = "overlay";
    feedback_widget_options.company = "dunia_au";
    feedback_widget_options.placement = "left";
    feedback_widget_options.color = "#222";
    feedback_widget_options.style = "idea";

    var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>
</body>
</html>