<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <?php
$this->headLink()
	->appendStylesheet($this->baseUrl('contrib/adapt-960/assets/css/960.css'), 'screen, projection')
	->appendStylesheet($this->baseUrl('contrib/blueprint/blueprint/ie.css'), 'screen, projection', "lte IE 9")
	->appendStylesheet($this->baseUrl('contrib/blueprint/blueprint/plugins/link-icons/screen.css'), 'screen, projection')
	->appendStylesheet($this->baseUrl('contrib/blueprint/blueprint/plugins/sprites/sprite.css'), 'screen, projection')
	->appendStylesheet($this->baseUrl('contrib/tablesorter/blue/style.css'), 'screen, projection')
    ->appendStylesheet($this->baseUrl('/contrib/jquery-ui-1.8.17.custom/css/custom-theme/jquery-ui-1.8.17.custom.css'), 'screen, projection')
    ->appendStylesheet($this->baseUrl('css/jquery.lightbox-0.5.css'), 'screen, projection')
    ->appendStylesheet($this->baseUrl('/css/formalize/formalize.css'), 'screen, projection')
    ->appendStylesheet($this->baseUrl('css/style.css'), 'screen, projection')
;
$this->headScript()
    ->appendFile( '/contrib/jquery-ui-1.8.17.custom/js/jquery-ui-1.8.17.custom.min.js')
	->appendFile($this->baseUrl('js/jquery.lightbox-0.5.min.js'))
    ->appendFile( '/js/jquery.sticky.js')
    ->appendFile( '/js/formalize/jquery.formalize.js')
    ->appendFile('/js/jquery.tools.min.js')
	->appendFile($this->baseUrl('contrib/1140_CssGrid_2/js/css3-mediaqueries.js'))
;
?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<script type="text/javascript">
<!--
thirsty = {};
//-->
</script>
</head>
<body>
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '379208815457293',
            status     : true,
            cookie     : true,
            xfbml      : true,
            oauth      : true
          });
        };
        (function(d) {
            var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
            js = d.createElement('script'); js.id = id; js.async = true;
            js.src = "//connect.facebook.net/en_US/all.js";
            d.getElementsByTagName('head')[0].appendChild(js);
         } (document));
    </script>
    <div id="header">
    <div class="container_12">
        <div class="grid_1">
            <a id="logo" href="/">Dunia</a>
        </div>
    	<div class="grid_11 omega">
	    	<div id="nav">
				<?php echo $this->render('partials/nav.phtml'); ?>
	    	</div>
    	</div>
    </div>
    </div>
    <?php echo $this->layout()->content; ?>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-30515404-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
    
    <script type="text/javascript">
	<!--
	$(document).ready(function(){
	    $(".sticky").sticky({topSpacing:0});
	});
	//-->
	</script>
</body>
</html>