<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		<?php
		    $this->headLink()->appendStylesheet($this->baseUrl('contrib/adapt-960/assets/css/960.css'), 'screen, projection');
		?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
		<script type="text/javascript">
		</script>
	</head>
	<body>
	 <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '373246349359082',
            status     : true,
            cookie     : true,
            xfbml      : true,
            oauth      : true
          });
        };
        (function(d){
           var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/en_US/all.js";
           d.getElementsByTagName('head')[0].appendChild(js);
         }(document));
      </script>
	<?php echo $this->layout()->content; ?>
	</body>
</html>