<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		<?php
		$this->headLink()->appendStylesheet($this->baseUrl('contrib/adapt-960/assets/css/960.css'), 'screen, projection');
		?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
		<script type="text/javascript">
		<!--
		thirsty = {};
		//-->
		</script>
	</head>
	<body>
	<?php echo $this->layout()->content; ?>
	</body>
</html>