<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>Dunia | Happy Hours and Daily Pub Deals in Sydney | Cheap beer, wine, spirits</title>

        <meta name="description" content="Dunia brings you the most interesting Happy Hours and Pub deals in the city of Sydney, Australia. Cheap beer, wine and spirits.">

        <!-- Mobile viewport optimized: j.mp/bplateviewport -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
<!--        <link rel="shortcut icon" href="/favicon.ico">-->
<!--        <link rel="apple-touch-icon" href="/apple-touch-icon.png">-->

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php if (APPLICATION_ENV == 'production'): ?>
		<script data-main="/js/main-build.js" src="/js/require.js"></script>
		<?php else: ?>
		<script data-main="/js/main.js" src="/js/require.js"></script>
		<?php endif; ?>
		
		<?php
		    $this->headLink()
                ->appendStylesheet($this->baseUrl('contrib/bootstrap/css/bootstrap.css'), 'screen, projection')
                ->appendStylesheet($this->baseUrl('contrib/bootstrap/css/bootstrap-responsive.css'), 'screen, projection')
                ->appendStylesheet($this->baseUrl('/contrib/jquery-ui-1.8.17.custom/css/custom-theme/jquery-ui-1.8.17.custom.css'), 'screen, projection')
                //->appendStylesheet($this->baseUrl('/css/formalize/formalize.css'), 'screen, projection')
                ->appendStylesheet('http://fonts.googleapis.com/css?family=Imprima', 'screen, projection')
                ->appendStylesheet($this->baseUrl('css/homepage.css'), 'screen, projection')
                ->appendStylesheet($this->baseUrl('css/style.css'), 'screen, projection')
            ;
		?>
		
		<?php echo $this->headScript(); ?>
	</head>
	<body>
	 <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '373246349359082',
            status     : true,
            cookie     : true,
            xfbml      : true,
            oauth      : true
          });
        };
        (function(d){
           var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/en_US/all.js";
           d.getElementsByTagName('head')[0].appendChild(js);
         }(document));
      </script>
	<?php echo $this->layout()->content; ?>
	</body>
    <?php echo $this->headLink(); ?>
    <?php echo $this->placeholder('js'); ?>
</html>