<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $this->windowTitle; ?></title>
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
		<meta name="keywords" content="keywords, here" />
		<meta name="description" content="description here" />
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<?php
			$this->headLink()->prependStylesheet($this->baseUrl('css/reset.css'));
			$this->headLink()->appendStylesheet($this->baseUrl('css/mobile.css'));
			$this->headLink()->appendStylesheet($this->baseUrl('css/jquery.mobile-1.0rc2.min.css'));
	        $this->headScript()->prependFile($this->baseUrl('js/jquery-1.6.4.min.js'));
	        $this->headScript()->appendFile($this->baseUrl('js/jquery.corner.js'));
	        $this->headScript()->appendFile($this->baseUrl('js/default.js'));
	        $this->headScript()->appendFile($this->baseUrl('js/jquery.mobile-1.0rc2.min.js'));
	        
		    echo $this->headLink();
		    echo $this->headScript(); ?>
        
	</head>
	<body>
        <div data-role="page">
    		<div data-role="header">
    			<h1><a href="<?php echo $this->baseUrl('/');?>">DOL Logo</a></h1>
    			
    			<ul id="topNav">
    			<?php if (!Zend_Auth::getInstance()->hasIdentity()): ?>
    			    <li><a href="<?php echo $this->baseUrl('/index/login');?>">Login</a></li> |
    			    <li><a href="<?php echo $this->baseUrl('/index/register');?>">Register</a></li>
    			<?php else: ?>
    				<li><a href="<?php echo $this->baseUrl('/index/profile');?>">Profile</a></li> |
    				<li><a href="<?php echo $this->baseUrl('/index/logout');?>">Logout</a></li>			    
    			<?php endif;?>
    			</ul>
            </div>
    		
    		<div data-role="content">
    			<?php echo $this->layout()->content; ?>
    		</div>
    		
    		<div data-role="footer">
    			<?php echo $this->partial('/partials/footer.php'); ?>
            </div>
        </div>
	</body>
</html>
