<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $this->windowTitle; ?></title>
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true&libraries=places"></script>
        
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        
		<meta name="keywords" content="keywords, here" />
		<meta name="description" content="description here" />
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<?php
			$this->headLink()->prependStylesheet($this->baseUrl('css/reset.css'));
			
			$this->headLink()->appendStylesheet($this->baseUrl('css/jquery.mobile-1.1.0-rc.css'));
			$this->headLink()->appendStylesheet($this->baseUrl('css/mobile.css'));
			
	        $this->headScript()->prependFile($this->baseUrl('js/jquery-1.6.4.min.js'));
	        $this->headScript()->appendFile($this->baseUrl('js/jquery.corner.js'));
	        $this->headScript()->appendFile($this->baseUrl('js/default.js'));
	        $this->headScript()->appendFile($this->baseUrl('js/jquery.mobile-1.1.0-rc.min.js'));
	        $this->headScript()->appendFile($this->baseUrl('js/jquery.ui.map.full.min.js'));
	        
		    echo $this->headLink();
		    echo $this->headScript(); ?>
		    
	</head>
	<body>
        <div data-role="page">
    		<div id="home" data-role="header" data-add-back-btn="true">
    			<h1><img src="/img/dunia.png" width="82" height="25"/></h1>
    			<a href="/index/map" class="ui-btn-right" data-theme="a" rel="external"><img src="/img/icons/navbar/103-map.png" height="21" width="26"></a>
            </div>
    		
    		<div data-role="content">
    			<?php echo $this->layout()->content; ?>
    		</div>
    		
    		<div id="footer" data-role="footer">

            </div>
        </div>
	</body>
</html>
