<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $this->windowTitle; ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
		<meta name="keywords" content="keywords, here" />
		<meta name="description" content="description here" />
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<style type="text/css">
    		html { height: 100% }
    		body { height: 100%; margin: 0; padding: 0 }
		</style>
		<?php
			$this->headLink()->prependStylesheet($this->baseUrl('css/reset.css'));
			
			$this->headLink()->appendStylesheet($this->baseUrl('css/jquery.mobile-1.1.0.min.css'));
			$this->headLink()->appendStylesheet($this->baseUrl('css/mobile.css'));
			
	        $this->headScript()->prependFile($this->baseUrl('js/jquery-1.6.4.min.js'));
            $this->headScript()->appendFile($this->baseUrl('js/jquery.mobile-1.1.0.min.js'));
            $this->headScript()->appendFile($this->baseUrl('js/jquery.ui.map.full.min.js'));
            $this->headScript()->appendFile($this->baseUrl('js/default.js'));

		    echo $this->headLink();
		    echo $this->headScript(); ?>
		    
	</head>
	<body>
		<?php echo $this->layout()->content; ?>
	</body>
</html>
