<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" style="display: inline;">
    <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
    <a class="addthis_button_tweet"></a>
    <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
    <a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f93fc3233f490f0&async=1"></script>
<?php $this->placeholder('js')->captureStart(); ?>
<script type="text/javascript">
    $(document).ready(function() {
        addthis.init();
    });
</script>
M<?php $this->placeholder('js')->captureStart(); ?>