<?php
    $auth = Aw_Auth::getInstance();
    if ($auth->hasIdentity()) :
        $session = new Zend_Session_Namespace('user');
        $user    = $session->user;
?>
    <a href="/user/logout">Logout</a>
    <a href="/user/profile" id="profile-nav"><img src="<?php echo $user->avatar; ?>" width="23" height="23" /><?php echo $user->firstName; ?></a>
    <?php else: ?>
    <a href="/user/login">Login</a>
    <?php endif; ?>
<a href="#">Tell a friend</a>
<a href="/pub/">Pubs Index</a>
<a href="<?php echo $this->url(array('controller' => 'pub', 'action' => 'email')); ?>">Mail Share</a>
