<div class="nav-collapse">
    <ul class="nav pull-right">
        <li><a href="<?php echo $this->url(array('controller' => 'pub', 'action' => 'email')); ?>" id="mailShare">Mail Share</a></li>
        <li><a href="/pub/">Pubs Index</a></li>
        <li><a href="http://www.dunia.com.au/blog/about-us" target="_blank">About us</a></li>
        <?php
        $auth = Aw_Auth::getInstance();
        if ($auth->hasIdentity()) :
            $session = new Zend_Session_Namespace('user');
            $user    = $session->user;
        ?>
            <li><a href="/user/profile" id="profile-nav"><img src="<?php echo ($user->avatar ?: sprintf('http://www.gravatar.com/avatar/%s?s=23&d=mm&r=g', md5($user->email))); ?>" width="23" height="23" class="img-polaroid" style="width: 23px; height: 23px;" /><?php echo ($user->firstName ?: $user->email); ?></a></li>
            <li><a href="/user/logout">Logout</a></li>
        <?php else: ?>
            <li><a id="login-link" href="#">Login</a></li>
        <?php endif; ?>
        <li><a href="/index/help" id="help">Help</a></li>
    </ul>
</div>
