<?php
    $days   = Model_Day::$days;
    $promos = $this->pub->getPromos();
?>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <?php foreach ($days as $day): ?>
                <th><?php echo $day; ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
        <?php $days = array_flip(Model_Day::$days); ?>
        <?php foreach($promos as $promo): ?>
            <?php
            $prev = $curr = $key = null;
            $cols = array();

            foreach(explode(",", $promo->day) as $index => $day) {
                $curr = $days[$day];
                if ($curr - 1 === $prev) {
                    $cols[$key]++;
                } else {
                    $key = $day;
                    $cols[$key] = 1;
                }
                $prev = $curr;
            }
            ?>
        <tr>
        
        <?php foreach($days as $index => $value): ?>
            <?php if(isset($cols[$index])): ?>
                <?php $skip = $cols[$index] - 1; ?>
                <td colspan="<?php echo $cols[$index]; ?>">

                    <div class="promo glow">
                        <div class="time">
                            <?php echo $this->formatDate($promo->timeStart, 'g:ia'); ?> - <?php echo $this->formatDate($promo->timeEnd, 'g:ia'); ?>
                        </div>
                        <div class="thePromo">
                            <span class="price"><?php echo $this->currency($promo->price, null, null, $superIndex = true); ?></span>
                            <?php foreach ($promo->getLiquorTypes() as $liquor) {
                                echo ' <span class="liquorType">' . $liquor->name . "</span>";
                                $size = $promo->getLiquorSizes();
                                echo '<div class="liquorSize">';
                                foreach ($size as $s) {
                                    echo ' (' . $s['name'] . ')';
                                    break;
                                }
                                echo '</div>';
                                echo '<div class="promoDescription">' . $promo->description . '</div>';
                            } ?>
                        </div>
                    </div>

                </td>
            <?php else: ?>
                <?php
                    if (isset($skip) && $skip) {
                        $skip--;
                    } else {
                        echo '<td></td>';
                    } ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </tr>
        <?php endforeach; ?>
        
        <?php if(count($promos) == 0): ?>
        <tr><td colspan="7">There is no happy hour for this pub, help us out by filling in a happy hour in the form below.</td></tr>
        <?php endif; ?>
    </tbody>
</table>