<div class="container_12 content">
    <div class="grid_3"><?php echo $this->partial('admin/partials/admin-menu.phtml', array('actions' => $this->methods, 'current' => $this->current)); ?></div>
	<div class="grid_9">
		<table class="generic">
		<caption>Non processed flags</caption>
			<thead>
				<tr>
					<th>Pub</th>
                    <th>Type</th>
                    <th>Change</th>
					<th>Reporter</th>
                    <th width="40"></th>
				</tr>
			</thead>
			<tbody>
                <?php foreach ($this->flags as $flag): ?>
	    			<tr>
                        <td><a href="/pub/overview/id/<?php echo $flag->idPub; ?>"><?php echo $flag->name; ?></a></td>
                        <td><?php echo Model_Flag::$flagType[$flag->type]; ?></td>
                        <td>--Data--</td>
                        <td><?php echo $flag->login ? $flag->login : 'Anonymous'; ?></td>
                        <td><a class="ok small-icon" href="#">Accept</a> <a class="cancel small-icon" href="#">Reject</a></td>
                    </tr>
                <?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>