<div class="container content" id="mailshare">

    <div class="row">
        <div id="sidebar-row" class="span12">
            <h1>Mail Share</h1>
        </div>
    </div>

    <?php // This chunk is ugly but at the moment it's the best I can get with bootstrap that is responsive design
        $i = 0;
        foreach($this->forms as $index => $form):
            if (!($i%3)):
    ?>
        <div class="row-fluid">
            <ul class="thumbnails">
    <?php
            endif;
            $i++;
    ?>
            <li class="span4" >
                <div class="thumbnail">
                    <div style="padding: 0 10px;">
                        <?php echo $form; ?>
                    </div>
                </div>
            </li>
    <?php
            if (!($i%3)):
    ?>
            </ul>
        </div>
    <?php
            endif;
        endforeach;
    ?>
</div>
<script type="text/javascript">
<!--
var config = {
    url: "<?php echo $this->url(array('action' => 'overview', 'controller' => 'pub', 'id' => '')); ?>"
};
//-->
</script>
