<?php $this->headScript()
	->appendFile($this->baseUrl('js/jquery.form.js'));
?>

<div class="container_12" id="mailshare">

<div class="grid_12">
<p>Note: Use this only for merging pictures, because merging all data could be hard and i ain't good programmer.</p>
</div>

<?php foreach($this->forms as $index => $form): ?>
	<div class="grid_4" >
		<?php echo $form; ?>
	</div>
<?php endforeach; ?>
	
</div>
<script type="text/javascript">
<!--
$().ready(function() {
	var $table = $('#mailshare');
	$("input[name='subject']", $table).autocomplete({
		source: '/pub/search/format/json',
		select: function (event, ul) {
			var $this = $(this);
			$form = $this.parents('form');
			$('input[name="hidden"]', $form).val(ul.item.id);
			$('input[type="submit"]', $form).enable(true);
		}
	});
	
	$('form', $table).ajaxForm({success: function(responseText, statusText, xhr, $form) {
		var data = jQuery.parseJSON(responseText);
		$('.delete', $form).unbind('click').html('<a target="_blank" href="<?php echo $this->url(array('action' => 'share', 'controller' => 'pub', 'id' => '')); ?>' + data.id + '">Go to Pub Edit Page</a>');
	}});
	
	$('input[type="submit"]', $table).enable(false);
	
	$(".delete").click(function(e) {
		e.preventDefault();
		var $this = $(this);
		var id = $this.attr('data-mail');
		$.get('/mailshare/delete/id/' + id);
		$this.parents('div.grid_6').fadeOut();
	});

	$('#mailshare form .image-region a.image').lightBox({fixedNavigation:true});
	
});
//-->
</script>