<div class="container content">
    <div class="row">
        <div class="span3">
            <h1>Pubs Index</h1>
        </div>
        <?php foreach($this->stateProgress as $key => $progress): ?>
        <div class="span1 state-progress">
            <span><?php echo strtoupper($key); ?> <?php printf('%d/%d', $progress[0], $progress[1]); ?></span>
            <div class="progress progress-striped">
                <div class="bar" style="width: <?php echo ($progress[0] ? $progress[0] / $progress[1]: 0); ?>%;"></div>
            </div>
        </div>
        <?php endforeach; ?>
        <div class="span5">
            <form action="" method="get" class="pull-right">
                <input id="tags" type="text" 1name="q" autocomplete="off" autofocus="autofocus" style="margin-top: 12px;" /> <input type="submit" value="Search">
                <button type="button" id="new-pub">New</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <table class="table table-striped table-bordered table-condensed" cellspacing="1px" cellpadding="0px" border="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Url</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th colspan="4">
                            <?php echo $this->pubs; ?>
                        </th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php foreach($this->pubs as $pub): ?>
                    <tr>
                        <td><a href="<?php echo  $this->url(array('id' => $pub->id, 'action' => 'overview')); ?>" class="ss_sprite ss_application_edit"><?php echo $pub; ?></a></td>
                        <td><?php echo $pub->getAddress()->formatOutput(' '); ?></td>
                        <td><a href="<?php echo $pub->url; ?>" target="_blank"><?php echo $pub->url; ?></a></td>
                        <td><?php echo ($pub->isChecked ? '&#10004;': null); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>