<script type="text/javascript">
<!--
$(function() {
	$( "#tags" ).autocomplete({
		source: '/pub/search/format/json',
		select: function (event, ul) {
			document.location = '/pub/overview/id/' + ul.item.id;
		}
	});

	$("#new-pub").click(function() {
		document.location = "/pub/overview/name/" + encodeURIComponent($( "#tags" ).val());
	});
});
//-->
</script>

<div class="container content">
    <div class="row">
        <div class="span3">
            <h1>Pubs Index</h1>
        </div>
        <div class="span9">
            <form action="" method="get" class="formalize pull-right">
                <a href="<?php echo $this->url(array('checked' => $this->reversi)); ?>"><span class="label <?php echo ($this->reversi ? null: 'label-success'); ?>">Uncheced Only</span></a>
                <input id="tags" type="text" 1name="q" autocomplete="off" autofocus="autofocus" style="margin-top: 12px;" /> <input type="submit" value="Search">
                <button type="button" id="new-pub">New</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <table class="generic" cellspacing="1px" cellpadding="0px" border="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th colspan="3">
                            <?php echo $this->pubs; ?>
                        </th>
                    </tr>
                </tfoot>
                <tbody>
                    <?php foreach($this->pubs as $pub): ?>
                    <tr>
                        <td><a href="<?php echo  $this->url(array('id' => $pub->id, 'action' => 'overview')); ?>" class="ss_sprite ss_application_edit"><?php echo $pub; ?></a></td>
                        <td><?php echo $pub->getAddress()->formatOutput(' '); ?></td>
                        <td><?php echo ($pub->isChecked ? '&#10004;': null); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>