<?php $address = $this->pub->address; ?>

<div class="pub-overview container_12 content">

    <div class="grid_6">
        <h1><?php echo $this->pub->name; ?></h1>
        
        <?php
            $days   = Model_Day::$days;
            $promos = $this->pub->getPromosByDay();
        ?>
        
		<div id="edit-section">
		<?php if($this->pubRow): ?>
			<div class="sticky-style grid_6 alpha" id="image-region">
			<?php foreach($this->pubRow->getImagesWebUri() as $image): ?>
				<a class="image" href="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=600"><img src="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=100" alt="" /></a>
			<?php endforeach; ?>
			</div>
		<?php endif; ?>
		<?php echo $this->form; ?>
		</div>

        <?php
        $images = $this->pub->getImageLinks();

        if (count($images)) : ?>
        <div id="photos">
            <h2>Photos</h2>
            <ul>
                <?php
                foreach ($images as $img) {
                    echo '<li>
                        <a href="/phpThumb/phpThumb.php?src=' . $img . '&amp;w=600&amp;ar=x">
                            <img class="venuePic" src="/phpThumb/phpThumb.php?src=' . $img . '&amp;w=125&amp;h=125&amp;zc=1&amp;ar=x"/>
                        </a>
                        </li>';
                } ?>
            </ul>
        </div>
        <?php endif; ?>



        <?php
        $tips = $this->pub->getTips();
        if (count($tips)): ?>

        <div id="tips">
            <h2>Tips
                <div class="right">
                    <img src="/img/icons/social/poweredByFoursquare_gray.png" width="128" height="14" />
                    </div>
            </h2>

            <ul>
                <?php foreach ($tips as $tip) { ?>
                    <li>
                        <div class="tip-container">
                        <div class="author">
                            <?php $data = json_decode($tip->data); ?>
                            <div>
                                <a href="<?php echo $data->user->canonicalUrl;?>">
                                    <img src="<?php echo $data->user->photo;?>" width="60" height="60"/>
                                </a>
                            </div>
                            <div class="name""><?php echo (isset($data->user->firstName) ? $data->user->firstName : '') . ' ' . (isset($data->user->lastName) ? $data->user->lastName : ''); ?></div>
                            <div class="from"><?php echo '(' . $data->user->homeCity . ')'; ?></div>
                        </div>
                        <div class='tip'>
                            <?php echo $tip->text; ?>
                        </div>
                        </div>
                    </li>
                <?php } ?>
            </ul>
        </div>
        <?php endif;?>
        
    </div>

    <div class="grid_6 sidebar omega" id="overview-sidebar">
        <div>
            <div id="map_canvas" style="width: 100%; height: 200px;"></div>
            <div class="contact">
                <span class="address"><?php echo $address->formatOutput(' '); ?></span>
    			<a href="<?php echo $this->pub->url; ?>"><?php echo $this->pub->url; ?></a>
    			<a href="mailto:<?php echo $this->pub->email; ?>"><?php echo $this->pub->email; ?></a>
    		</div>
        </div>
        <?php echo $this->partial('partials/addthis.phtml'); ?>
        
        
        <table id="promos" class="generic" cellspacing="1px" cellpadding="0px" border="0">
	    <caption><a href="#" id="edit-section-button" class="ss_sprite ss_application_edit pad"></a></caption>
            <thead>
                <tr>
                    <?php foreach ($days as $day): ?>
                        <th><?php echo $day; ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <tr>
                <?php foreach ($days as $dayInt => $day): ?>
                    <td width="<?php echo (1/sizeof($days)) * 100; ?>%">
                    <?php if (isset($promos[$dayInt])) {
                        foreach ($promos[$dayInt] as $promo): ?>
                            <div class="promo">
                                <div class="time">
                                    <?php echo $this->formatDate($promo->timeStart, 'H:i'); ?> - <?php echo $this->formatDate($promo->timeEnd, 'H:i'); ?>
                                </div>
                                <div class="promoContent"><strong><?php echo $this->currency($promo->price); ?></strong><br />
                                    <?php foreach ($promo->getLiquorTypes() as $liquor) {
                                        echo ' ' . $liquor->name;
                                        $size = $promo->getLiquorSizes();
                                        foreach ($size as $s) {
                                            echo ' (' . $s['name'] . ')';
                                        }
                                        echo '<div class="promoDescription">' . $promo->description . '</div>';
                                    } ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php } ?>
                    </td>
                <?php endforeach; ?>
                </tr>
            </tbody>
        </table>
        
    </div>
</div>

<div id="dialog"></div>

<script type="text/javascript">

$(document).ready(function() {

	$('#edit-section-button').click(function(e) {
		e.preventDefault();
		$.scrollTo($('#edit-section'), 500);
	});
 
    var center = new google.maps.LatLng(parseFloat(<?php echo $address->latitude; ?>), parseFloat(<?php echo $address->longitude; ?>));
    var myOptions = {
        zoom: 16,
        center: center,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    new google.maps.Marker({
        map: map,
        position: center
    });

    $('#dialog').dialog({
        autoOpen: false,
        width: 650,
        position: ['center', 100]
    });

    $("#flag a").click(function() {
        $.ajax({
            url: '/pub/flag',
            data: {idPub: <?php echo $this->pub->id; ?>},
            success: function (data) {
                $('#dialog').html(data);
                $('#dialog').dialog('open');
            }
        })
        return false;
    });

    $('#photos a').lightBox();

});
</script>

		<script type="text/javascript">
		$(function() {
			$('a.open').click(function() {
				popup = window.open($('#url').val() , 'popup', 'height=600,width=800');
				if (window.focus) { popup.focus(); }
				return false;
			});
		
			$('form fieldset legend > a').click(function(e) {
				e.preventDefault();
				var $this = $(this);
				$this.parents('fieldset').remove();
			});
		
			$('#image-region a.image').lightBox({fixedNavigation:true});
		
			$("#image-region").sticky({topSpacing:52});

			$("#overview-sidebar").sticky({topSpacing: 0});
		});
		</script>




<?php $this->headScript()->appendFile('/js/jquery.scrollTo-min.js'); ?>