<?php $address = $this->pub->address; ?>

<div class="pub-overview container_12 content">

	
    
    <div class="grid_6">
        <h1><?php echo $this->pub->name; ?></h1>
        <script type="text/x-handlebars">
            {{#view App.tipsView}}
			 <div class="right">
                 <img src="/img/icons/social/poweredByFoursquare_gray.png" width="128" height="14" />
			 </div>
                {{#collection tipsCollectionView}}
				<li>
					<div class="tip-container">
                        <div class="author">
							<div class="image">
                                <a {{bindAttr href="content.user.canonicalUrl"}}>
                                    <img style="float: left" {{bindAttr src="content.user.photo"}} width="60" height="60"/>
									{{content.text}}
									<br />
									<b>{{content.user.firstName}} {{content.user.lastName}} &rarr; {{content.user.homeCity}}</b>
                                </a>
                            </div>
						</div>
					</div>
					<div style="clear: both"></div>
				</li>
                {{/collection}}
            {{/view}}
        </script>
        
        <?php
            $days   = Model_Day::$days;
            $promos = $this->pub->getPromosByDay();
        ?>
        
		<div id="edit-section">
		<?php if($this->pubRow): ?>
			<div class="sticky-style grid_6 alpha" id="image-region">
			<?php foreach($this->pubRow->getImagesWebUri() as $image): ?>
				<a class="image" href="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=600"><img src="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=100" alt="" /></a>
			<?php endforeach; ?>
			</div>
		<?php endif; ?>
		<?php echo $this->form; ?>
		</div>
        
    </div>

    <div class="grid_6 sidebar omega" id="overview-sidebar">
        <div>
            <div id="map_canvas" style="width: 100%; height: 200px;"></div>
            <div class="contact">
                <span class="address"><?php echo $address->formatOutput(' '); ?></span>
    			<a href="<?php echo $this->pub->url; ?>"><?php echo $this->pub->url; ?></a>
    			<a href="mailto:<?php echo $this->pub->email; ?>"><?php echo $this->pub->email; ?></a>
    		</div>
        </div>
        <?php echo $this->partial('partials/addthis.phtml'); ?>
        
        
        <table id="promos" class="generic" cellspacing="1px" cellpadding="0px" border="0">
	    <caption><a href="#" id="edit-section-button" class="ss_sprite ss_application_edit pad"></a></caption>
            <thead>
                <tr>
                    <?php foreach ($days as $day): ?>
                        <th><?php echo $day; ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <tr>
                <?php foreach ($days as $dayInt => $day): ?>
                    <td width="<?php echo (1/sizeof($days)) * 100; ?>%">
                    <?php if (isset($promos[$dayInt])) {
                        foreach ($promos[$dayInt] as $promo): ?>
                            <div class="promo">
                                <div class="time">
                                    <?php echo $this->formatDate($promo->timeStart, 'H:i'); ?> - <?php echo $this->formatDate($promo->timeEnd, 'H:i'); ?>
                                </div>
                                <div class="promoContent"><strong><?php echo $this->currency($promo->price); ?></strong><br />
                                    <?php foreach ($promo->getLiquorTypes() as $liquor) {
                                        echo ' ' . $liquor->name;
                                        $size = $promo->getLiquorSizes();
                                        foreach ($size as $s) {
                                            echo ' (' . $s['name'] . ')';
                                        }
                                        echo '<div class="promoDescription">' . $promo->description . '</div>';
                                    } ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php } ?>
                    </td>
                <?php endforeach; ?>
                </tr>
            </tbody>
        </table>
        
    </div>
</div>

<div id="dialog"></div>

<script type="text/javascript">

$(document).ready(function() {

    var center = new google.maps.LatLng(parseFloat(<?php echo $address->latitude; ?>), parseFloat(<?php echo $address->longitude; ?>));
    var myOptions = {
        zoom: 16,
        center: center,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

    new google.maps.Marker({
        map: map,
        position: center
    });

    $('#dialog').dialog({
        autoOpen: false,
        width: 650,
        position: ['center', 100]
    });

    $("#flag a").click(function() {
        $.ajax({
            url: '/pub/flag',
            data: {idPub: <?php echo $this->pub->id; ?>},
            success: function (data) {
                $('#dialog').html(data);
                $('#dialog').dialog('open');
            }
        })
        return false;
    });

    $('#photos a').lightBox();

    $('#edit-section-button').click(function(e) {
		e.preventDefault();
		$.scrollTo($('#edit-section'), 500);
	});
	

    $('a.open').click(function() {
		popup = window.open($('#url').val() , 'popup', 'height=600,width=800');
		if (window.focus) { popup.focus(); }
		return false;
	});

	$('form fieldset legend > a').click(function(e) {
		e.preventDefault();
		var $this = $(this);
		$this.parents('fieldset').remove();
	});

	$('#image-region a.image').lightBox({fixedNavigation:true});

	$("#image-region").sticky({topSpacing:52});

	$("#overview-sidebar").sticky({topSpacing: 0});

	AppClass = Ember.Application.extend({
		ready: function() {
			this.AppController.initialize(<?php echo json_encode($this->pubRow->toArray()); ?>);
		},
	});

	App = AppClass.create();

	App.TipProxyClass = Ember.ArrayProxy.extend({
		
	});

	App.TipClass = Ember.Object.extend();

	App.AppControllerClass = Ember.Object.extend({
		row: null,
		tips: App.TipProxyClass.create({content: []}),
		tipUrl: '<?php echo $this->url(array('controller' => 'foursquare', 'action' => 'fetch-tips'), null, true); ?>',
		initialize: function(data) {
			this.row = data;
			this.loadTips();
		},
		loadTips: function() {
			var $this = this;
			$.ajax({
				url: this.tipUrl,
				data: {idFoursquare: this.row.idFoursquare},
				success: function(data) {
					data.forEach(function(value, index) {
						App.TipClass.create(value);
						$this.tips.pushObject(App.TipClass.create(value));
					})
				}
			});
		}
	});

	
	
	App.AppController = App.AppControllerClass.create({});

	App.tipsView = Ember.View.extend({
		tipsCollectionView: Ember.CollectionView.extend({
			tagName: 'ul',
            contentBinding: 'App.AppController.tips',
            itemViewClass: Ember.View.extend({
            	tagName: '',
            })
		})
	});

});
</script>
<?php $this->headScript()->appendFile('/js/jquery.scrollTo-min.js'); ?>