<?php $address = $this->pub->address;?>

<script type="text/javascript">
	$(document).ready(function() {
    	var pub = { 'center': '<?php echo $address->latitude . ',' . $address->longitude; ?>', 'zoom': 16 };


    	$('#map_canvas').gmap({'center': pub.center, 'zoom': pub.zoom, 'disableDefaultUI':true, 'callback': function() {
    		var self   = this;
            var bounds = new google.maps.LatLngBounds();

            var position = new google.maps.LatLng(<?php echo $address->latitude . ',' . $address->longitude; ?>);
            bounds.extend(position);
    		self.addMarker({'position': new google.maps.LatLng(<?php echo $address->latitude . ',' . $address->longitude; ?>) }).click(function() {
    			self.openInfoWindow({ 'content': '<?php echo addslashes($this->pub->name); ?>' }, this);
    		});

    		if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {

                    var longitude = position.coords.longitude;
                    var latitude  = position.coords.latitude;

					var currentPosition = new google.maps.LatLng(latitude, longitude);
                    bounds.extend(currentPosition);

                	self.addMarker({'position': currentPosition, icon:'/img/icons/markers/current.png' }).click(function() {
            			self.openInfoWindow({ 'content': '<?php echo addslashes($this->pub->name); ?>' }, this);
            		});
                	self.get('map').fitBounds(bounds);
                    $('#directions').attr('href','http://maps.google.com/maps?dirflg=w&saddr=' + latitude + ',' + longitude + '&daddr=<?php echo $address->latitude . ',' . $address->longitude; ?>');
                });
            }


        }});

        $("#maptab").live('pageshow', function() {
            $('#map_canvas').gmap('refresh');
        });

});
</script>

<div data-role="page" id="deals">
	<div class="home" data-role="header">
        <a href="/" class="navButton" data-role="none" data-transition="slide">
            <img src="/img/icons/navbar/53-house-shadow.png" width="24" height="28" />
        </a>
		<h1><?php echo $this->pub->name; ?></h1>
    </div>
	
	<div data-role="content">
        <h2>Deals</h2>
    	<?php
        $days   = Model_Day::$daysName;
        $promos = $this->pub->getPromosByDay();
    	if (count($promos)) {
            // Show today's deals first
            if (isset($promos[date('N')])) { ?>
                <h3>Today</h3>

                <ul data-role="listview" data-inset="true" data-theme="c">
                    <?php echo $this->partial('partials/deal.php', array('promos' => $promos[date('N')])); ?>
                </ul>
            <?php
                unset($promos[date('N')]);
            }

            if (count($promos)) {
                foreach ($promos as $day => $dailyPromos) { ?>
                    <h3><?php echo $days[$day]; ?></h3>

                    <ul data-role="listview" data-inset="true" data-theme="c">
                        <?php echo $this->partial('partials/deal.php', array('promos' => $promos[$day])); ?>
                    </ul>
                <?php
                }
            }

    	 } else { ?>
    	    <p>There are no deals for this venue yet. <a href="/deal/add/idPub/<?php echo $this->pub->id; ?>">Why don't you enter one?</a></p>
    	<?php }?>

        <h2>Contact</h2>
        <ul data-role="listview" data-inset="true" data-theme="c">
            <li><a href="<?php echo $this->pub->url; ?>"><img src="/img/icons/navbar/174-imac.png" alt="Website" class="ui-li-icon"> <?php echo $this->pub->url; ?></a></li>
            <li><a href="mailto:<?php echo $this->pub->email; ?>"><img src="/img/icons/navbar/123-id-card.png" alt="Email" class="ui-li-icon"> <?php echo $this->pub->email; ?></a></li>
        </ul>
	</div>
	
	<?php echo $this->partial('pub/partials/footer.php', array('selected' => 'beer'))?>
</div>



<div data-role="page" id="maptab" style="height:100%;">
	<div class="home" data-role="header">
        <a href="/" class="navButton" data-role="none" data-transition="slide">
            <img src="/img/icons/navbar/53-house-shadow.png" width="24" height="28" />
        </a>
		<h1><?php echo $this->pub->name; ?></h1>
    </div>
	
	<div data-role="content" style="height:100%;margin: 0;padding: 0">
		<div id="map_canvas" style="height:90%;"></div>
	</div>
	
    <?php echo $this->partial('pub/partials/footer.php', array('selected' => 'map'))?>
</div>



