<?php
    $address = $this->pub->address;
    $type    = $this->pub->pubType;
?>

<div class="container content">
    <div class="pub-overview row">
        <div class="span12">

            <h1>
                <?php if ($type && $type->icon) { echo '<img src="' . $type->icon . '" width="32" height="32" /> '; } echo $this->pub->name; ?>
            </h1>

            <div class="row">

                <div id="sidebar-row" class="span6">
                    <div class="sidebar" id="overview-sidebar">
                    <div class="details">
                        <div id="map_canvas" style="width: 100%; height: 200px;"></div>
                        <div class="contact">
                            <div class="address"><?php echo $address->formatOutput('<br />'); ?></div>
                            <div class="urls">
                                <div><a href="<?php echo $this->pub->url; ?>"><?php echo $this->pub->url; ?></a></div>
                                <div><a href="mailto:<?php echo $this->pub->email; ?>"><?php echo $this->pub->email; ?></a></div>
                            </div>
                        </div>
                    </div>

                    <div class="ribbon-wrapper">
                        <div class="ribbon-front">
                            <h2>Weekly Specials</h2>
                        </div>
                        <div class="ribbon-edge-topleft"></div>
                        <div class="ribbon-edge-topright"></div>
                        <div class="ribbon-edge-bottomleft"></div>
                        <div class="ribbon-edge-bottomright"></div>
                        <div class="ribbon-back-left"></div>
                        <div class="ribbon-back-right"></div>
                    </div>

                    <?php
                        $days   = Model_Day::$days;
                        $promos = $this->pub->getPromos();
                    ?>
                    <table id="promos" class="generic" cellspacing="1px" cellpadding="0px" border="0">
                    <caption><a href="#" id="edit-section-button" class="ss_sprite ss_application_edit pad"></a></caption>
                        <thead>
                            <tr>
                                <?php foreach ($days as $day): ?>
                                    <th><?php echo $day; ?></th>
                                <?php endforeach; ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $days = array_flip(Model_Day::$days); ?>
                            <?php foreach($promos as $promo): ?>
                                <?php
                                $prev = $curr = $key = null;
                                $cols = array();

                                foreach(explode(",", $promo->day) as $index => $day) {
                                    $curr = $days[$day];
                                    if ($curr - 1 === $prev) {
                                        $cols[$key]++;
                                    } else {
                                        $key = $day;
                                        $cols[$key] = 1;
                                    }
                                    $prev = $curr;
                                }
                                ?>
                            <tr>

                            <?php foreach($days as $index => $value): ?>
                                <?php if(isset($cols[$index])): ?>
                                    <?php $skip = $cols[$index] - 1; ?>
                                    <td colspan="<?php echo $cols[$index]; ?>">

                                        <div class="promo glow">
                                            <div class="time">
                                                <?php echo $this->formatDate($promo->timeStart, 'g:ia'); ?> - <?php echo $this->formatDate($promo->timeEnd, 'g:ia'); ?>
                                            </div>
                                            <div class="thePromo">
                                                <span class="price"><?php echo $this->currency($promo->price, null, null, $superIndex = true); ?></span>
                                                <?php foreach ($promo->getLiquorTypes() as $liquor) {
                                                    echo ' <span class="liquorType">' . $liquor->name . "</span>";
                                                    $size = $promo->getLiquorSizes();
                                                    echo '<div class="liquorSize">';
                                                    foreach ($size as $s) {
                                                        echo ' (' . $s['name'] . ')';
                                                        break;
                                                    }
                                                    echo '</div>';
                                                    echo '<div class="promoDescription">' . $promo->description . '</div>';
                                                } ?>
                                            </div>
                                        </div>

                                    </td>
                                <?php else: ?>
                                    <?php
                                        if (isset($skip) && $skip) {
                                            $skip--;
                                        } else {
                                            echo '<td></td>';
                                        } ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <br />
                    <?php echo $this->partial('partials/addthis.phtml'); ?>
                    </div>
                </div>

                <div id="content-row" class="span6">
                    <div style="padding-left: 10px;">
                        <?php
                        $images = $this->pub->getImageLinks();

                        if (count($images)) : ?>
                            <div id="photos">
                                <h2>Photos</h2>
                                <ul>
                                    <?php
                                    foreach ($images as $img) {
                                        echo '<li>
                                        <a href="/phpThumb/phpThumb.php?src=' . $img . '&amp;w=600&amp;ar=x">
                                            <img class="venuePic" src="/phpThumb/phpThumb.php?src=' . $img . '&amp;w=125&amp;h=125&amp;zc=1&amp;ar=x"/>
                                        </a>
                                        </li>';
                                    } ?>
                                </ul>
                            </div>
                            <?php endif; ?>

                        <script type="text/x-handlebars">
                            {{#view App.tipsView}}
                            <div id="tipsWrapper">

                                {{#collection tipsCollectionView}}
                                <li>
                                    <div class="tip-container">
                                        <div class="image" style="float: left" >
                                            <a clas {{bindAttr href="content.user.canonicalUrl"}}>
                                            <img {{bindAttr src="content.user.photo"}} width="40" height="40"/>
                                            </a>
                                        </div>
                                        <div>
                                            <div><a {{bindAttr href="content.user.canonicalUrl"}}>{{content.user.firstName}} {{content.user.lastName}}</a> <span class="date">{{content.date}}</span></div>
                                            <div>{{content.text}}</div>
                                        </div>
                                    </div>
                                    <div class="separator"></div>
                                </li>
                                {{/collection}}
                            </div>
                            {{/view}}
                        </script>

                        <div id="edit-section">
                            <?php if($this->pubRow): ?>
                            <div class="sticky-style alpha" id="image-region">
                                <?php foreach($this->pubRow->getImagesWebUri() as $image): ?>
                                <a class="image" href="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=600"><img src="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=100" alt="" /></a>
                                <?php endforeach; ?>
                            </div>
                            <?php endif; ?>
                            <?php echo $this->form; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

$(document).ready(function() {

    var center = new google.maps.LatLng(parseFloat(<?php echo $address->latitude; ?>), parseFloat(<?php echo $address->longitude; ?>));
    var myOptions = {
        zoom: 16,
        center: center,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    var markerShadow = new google.maps.MarkerImage('/img/icons/markers/marker-shadow.png', new google.maps.Size(41,41), new google.maps.Point(0,0), new google.maps.Point(13,41));

    new google.maps.Marker({
        map: map,
        position: center,
        icon: '/img/icons/markers/marker.png',
        shadow: markerShadow
    });

    $('#photos a').lightBox();

    $('#edit-section-button').click(function(e) {
		e.preventDefault();
		$.scrollTo($('#edit-section'), 500);
	});
	
    $('a.open').click(function() {
		popup = window.open($('#url').val() , 'popup', 'height=600,width=800');
		if (window.focus) { popup.focus(); }
		return false;
	});

	$('form fieldset legend > a').click(function(e) {
		e.preventDefault();
		var $this = $(this);
		$this.parents('fieldset').remove();
	});

	$('#image-region a.image').lightBox({fixedNavigation:true});

	$("#image-region").sticky({topSpacing: 52});

	//$("#overview-sidebar").sticky({topSpacing: 0});


	config = {
	    tipUrl: '<?php echo $this->url(array('controller' => 'foursquare', 'action' => 'fetch-tips'), null, true); ?>',
	    pub: <?php echo json_encode($this->pubRow->toArray()); ?>
	};

	AppClass = Ember.Application.extend({
		ready: function() {
			this.AppController.initialize(config.pub);
		}
	});

	App = AppClass.create();

	App.TipProxyClass = Ember.ArrayProxy.extend({
		
	});

	App.TipClass = Ember.Object.extend();

	App.AppControllerClass = Ember.Object.extend({
		row: null,
		tips: App.TipProxyClass.create({content: []}),
		tipUrl: config.tipUrl,
		initialize: function(data) {
			this.row = data;
			this.loadTips();
		},
		loadTips: function() {
			var $this = this;
			$.ajax({
				url: this.tipUrl,
				data: {idFoursquare: this.row.idFoursquare},
				success: function(data) {
                    if (data.length) {
                        data.forEach(function(value, index) {
                            value.user.canonicalUrl = 'https://foursquare.com/user/' + value.user.id;
                            value.date              = moment(value.createdAt * 1000).format('MMMM D, YYYY');

                            App.TipClass.create(value);
                            $this.tips.pushObject(App.TipClass.create(value));
                        });
                        $('#tipsWrapper').prepend('<h2>Tips' +
                            '<div class="right">' +
                            '<img src="/img/icons/social/poweredByFoursquare_gray.png" width="128" height="14" />' +
                            '</div>' +
                            '</h2>');
                    }
				}
			});
		}
	});

	App.AppController = App.AppControllerClass.create({});

	App.tipsView = Ember.View.extend({
		tipsCollectionView: Ember.CollectionView.extend({
			tagName: 'ul',
            contentBinding: 'App.AppController.tips',
            itemViewClass: Ember.View.extend({
            	tagName: ''
            })
		})
	});

	$('.promo.glow > .time[title]').tooltip();

});
</script>
<?php
    $this->headScript()->appendFile('/js/jquery.scrollTo-min.js');
    $this->headScript()->appendFile('/js/moment.min.js');
?>