<script>
	$(function() {
		$( "#tabs" ).tabs();
	});

</script>
<div class="container_12">
	<div class="grid_12">
		<div id="tabs">
			<ul>
				<li><a href="#tabs-1">By Form</a></li>
				<li><a href="#tabs-2">By Email</a></li>
				<li><a href="#tabs-3">By Foursquare</a></li>
			</ul>
			
			<div id="tabs-1" class="container_12">
				<div class="grid_6">
				<?php if($this->pub): ?>
					<div class="sticky-style grid_6 alpha" id="image-region">
					<?php foreach($this->pub->getImagesWebUri() as $image): ?>
						<a class="image" href="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=600"><img src="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=100" alt="" /></a>
					<?php endforeach; ?>
					</div>
				<?php endif; ?>
				<?php echo $this->form; ?>
				</div>
			</div>
			<div id="tabs-2">
					<h3>By Email</h3>
					Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
			</div>
			<div id="tabs-3">
					<h3>By Foursquae</h3>
					Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function() {
	$('a.open').click(function() {
		popup = window.open($('#url').val() , 'popup', 'height=600,width=800');
		if (window.focus) { popup.focus(); }
		return false;
	});

	$('form fieldset button[name*="delete"]').click(function() {
		var $this = $(this);
		$this.parents('fieldset').remove();
	});

	$('#image-region a.image').lightBox({fixedNavigation:true});

	$("#image-region").sticky({topSpacing:52});
});
</script>