<div class="container_12">
	<div class="grid_12">
		<div id="tabs-1" class="container_12">
			<div class="grid_6">
			<?php if($this->pub): ?>
				<div class="sticky-style grid_6 alpha" id="image-region">
				<?php foreach($this->pub->getImagesWebUri() as $image): ?>
					<a class="image" href="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=600"><img src="/phpThumb/phpThumb.php?src=<?php echo $image; ?>&amp;w=100" alt="" /></a>
				<?php endforeach; ?>
				</div>
			<?php endif; ?>
			<?php echo $this->form; ?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function() {
	$('a.open').click(function() {
		popup = window.open($('#url').val() , 'popup', 'height=600,width=800');
		if (window.focus) { popup.focus(); }
		return false;
	});

	$('form fieldset legend > a').click(function(e) {
		e.preventDefault();
		var $this = $(this);
		$this.parents('fieldset').remove();
	});

	$('#image-region a.image').lightBox({fixedNavigation:true});

	$("#image-region").sticky({topSpacing:52});
});
</script>