<?php

namespace D2Test\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Dol_Model_Entity_DealProxy extends \Dol_Model_Entity_Deal implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function addUserFavorite($user)
    {
        $this->_load();
        return parent::addUserFavorite($user);
    }

    public function clearDays()
    {
        $this->_load();
        return parent::clearDays();
    }

    public function __set($name, $value)
    {
        $this->_load();
        return parent::__set($name, $value);
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function toArray()
    {
        $this->_load();
        return parent::toArray();
    }

    public function hasAttribute($attr)
    {
        $this->_load();
        return parent::hasAttribute($attr);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'timeStart', 'timeEnd', 'dateStart', 'dateEnd', 'name', 'description', 'idUserSubmitted', 'days', 'types', 'userFavorites', 'reviews', 'flags', 'venue');
    }
}